### ISSUE TITLE
ghost api key exposed

### ISSUE THREAD

**Issue by readwy** [ddiu8081/ddiu.io#3]
### Describe the bug

Accessing the recent article API in Ghost is done on the client side, so the API key will be exposed. I am not sure how severe the risk is because I have not used this key for penetration testing.

### Reproduction

Minimal

### System Info

```Shell
browsers
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment]
Thank you. According to [Ghost Content API doc](https://ghost.org/docs/content-api/):

> These keys are safe for use in browsers and other insecure environments, as they only ever provide access to public data.
